//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSaveFormDemo.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClubs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblClubs()
        {
            this.TblStudents = new HashSet<TblStudents>();
        }
    
        public byte ClubID { get; set; }
        public string ClubName { get; set; }
        public Nullable<int> ClubQuota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudents> TblStudents { get; set; }
    }
}
