//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSaveFormDemo.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotes
    {
        public int NoteID { get; set; }
        public Nullable<byte> LessonID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<byte> Exam1 { get; set; }
        public Nullable<byte> Exam2 { get; set; }
        public Nullable<byte> Exam3 { get; set; }
        public Nullable<byte> Project { get; set; }
        public Nullable<decimal> Avarage { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual TblLessons TblLessons { get; set; }
        public virtual TblStudents TblStudents { get; set; }
    }
}
