//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSaveFormDemo.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblStudents()
        {
            this.TblNotes = new HashSet<TblNotes>();
        }
    
        public int StudentID { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public Nullable<decimal> StudentNote { get; set; }
        public string StudentFoto { get; set; }
        public Nullable<byte> StudentClub { get; set; }
        public string StudentGender { get; set; }
    
        public virtual TblClubs TblClubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblNotes> TblNotes { get; set; }
    }
}
